stages:
  - build
  - test

build windows/x64:
  stage: build
  script:
    - CMD.EXE /C ci\build-windows64.bat
  artifacts:
    when: always
    paths:
      - build
    expire_in: 3 days
  tags:
    - icsneo-windows

test windows/x64:
  stage: test
  script:
    - build\libicsneo-tests.exe
  dependencies:
    - build windows/x64
  needs:
    - build windows/x64
  tags:
    - icsneo-windows
  timeout: 3m

build windows/x86:
  stage: build
  script:
    - CMD.EXE /C ci\build-windows32.bat
  artifacts:
    when: always
    paths:
      - build
    expire_in: 3 days
  tags:
    - icsneo-windows

test windows/x86:
  stage: test
  script:
    - build\libicsneo-tests.exe
  dependencies:
    - build windows/x86
  needs:
    - build windows/x86
  tags:
    - icsneo-windows
  timeout: 3m